"""empty message

Revision ID: 1f8157eecb66
Revises: 59314f08cb4c
Create Date: 2024-04-21 12:26:33.800439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f8157eecb66'
down_revision: Union[str, None] = '59314f08cb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Parse sales', sa.Column('Href', sa.String(), nullable=False))
    op.add_column('Parse sales', sa.Column('Koords', postgresql.ARRAY(sa.DECIMAL()), nullable=False))
    op.add_column('Parse sales', sa.Column('Zagolovok', sa.TEXT(), nullable=True))
    op.add_column('Parse sales', sa.Column('Pod_zagolovok', sa.TEXT(), nullable=True))
    op.drop_column('Parse sales', 'link')
    op.drop_column('Parse sales', 'subdescription')
    op.drop_column('Parse sales', 'coordinates')
    op.drop_column('Parse sales', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Parse sales', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Parse sales', sa.Column('coordinates', postgresql.ARRAY(sa.NUMERIC()), autoincrement=False, nullable=False))
    op.add_column('Parse sales', sa.Column('subdescription', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Parse sales', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Parse sales', 'Pod_zagolovok')
    op.drop_column('Parse sales', 'Zagolovok')
    op.drop_column('Parse sales', 'Koords')
    op.drop_column('Parse sales', 'Href')
    # ### end Alembic commands ###
