"""'updated_user_table'

Revision ID: 2addf22c064f
Revises: 8adbe9e5ae09
Create Date: 2024-03-03 19:10:23.805008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2addf22c064f'
down_revision: Union[str, None] = '8adbe9e5ae09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users table', sa.Column('notifications', sa.Boolean(), nullable=True))
    op.add_column('Users table', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('Users table', sa.Column('radius', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users table', 'radius')
    op.drop_column('Users table', 'categories')
    op.drop_column('Users table', 'notifications')
    # ### end Alembic commands ###
