"""empty message

Revision ID: 77152cc98859
Revises: 7cf465ccd60f
Create Date: 2024-04-20 23:18:25.390400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77152cc98859'
down_revision: Union[str, None] = '7cf465ccd60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Parse sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('coordinates', postgresql.ARRAY(sa.DECIMAL()), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('subdescription', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Parse sales')
    # ### end Alembic commands ###
