"""second

Revision ID: 993eb342bfe4
Revises: e08656a7e376
Create Date: 2024-02-27 17:10:08.620108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993eb342bfe4'
down_revision: Union[str, None] = 'e08656a7e376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cookies', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cookies', 'session_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
